# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

bikesharingweb:
  ingress:
    annotations:
    hosts:
      - bikesharingweb.app.dev.synbee.it  # Assumes deployment to the 'dev' namespace

gateway:
  ingress:
    annotations:
    hosts:
      - gateway.app.dev.synbee.it   # Assumes deployment to the 'dev' namespace
